# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.AlterField(
            model_name='wikihometoplink',
            name='title',
            field=models.CharField(help_text=b'\xe9\x93\xbe\xe6\x8e\xa5\xe6\x98\xbe\xe7\xa4\xba\xe6\x96\x87\xe6\x9c\xac', max_length=255),
        ),
    ]
