# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170515_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': '页面最底部文本',
            },
        ),
        migrations.AlterField(
            model_name='wikihometoplink',
            name='title',
            field=models.CharField(help_text='链接显示文本', max_length=255),
        ),
    ]
